homeassistant:
  customize:
    sensor.garage_climate_oneline:
      icon: mdi:thermometer
    sensor.sensor1_oneline:
      icon: mdi:thermometer
    sensor.sensor2_oneline:
      icon: mdi:thermometer
    sensor.sensor3_oneline:
      icon: mdi:thermometer
    sensor.sensor4_oneline:
      icon: mdi:thermometer
    sensor.sensor5_oneline:
      icon: mdi:thermometer
    sensor.sensor6_oneline:
      icon: mdi:thermometer
    sensor.average_downstairs_temp:
      icon: mdi:thermometer
    sensor.average_upstairs_temp:
      icon: mdi:thermometer
    sensor.average_downstairs_humidity:
      icon: mdi:water-percent
    sensor.average_upstairs_humidity:
      icon: mdi:water-percent
      
 
## Hide Switches for Node Red Alexa Temperature Announcements 
    input_boolean.downstairs_temp:
      hidden: true
    input_boolean.downstairs_humidity:
      hidden: true
    input_boolean.garage_temp:
      hidden: true
    input_boolean.garage_humidity:
      hidden: true
    input_boolean.upstairs_temp:
      hidden: true
    input_boolean.upstairs_humidity:
      hidden: true  
## Hide rounded temp/humidty sensors alexa uses for announcements
    sensor.upstairs_temp_rounded:
      hidden: true
    sensor.upstairs_humidity_rounded:
      hidden: true
    sensor.downstairs_temp_rounded:
      hidden: true
    sensor.downstairs_humidity_rounded:
      hidden: true
    sensor.garage_temp_rounded:
      hidden: true
    sensor.garage_humidity_rounded:
      hidden: true
      
 
## Groups For Entities In This Package 
group:
  tempsensors:
    name: ' '
    view: no
    entities:
     - sensor.sensor1_oneline
     - sensor.sensor2_oneline
     - sensor.sensor3_oneline
     - sensor.sensor4_oneline
     - sensor.sensor5_oneline
     - sensor.sensor6_oneline
     - sensor.garage_climate_oneline
  hvac_stats_air:
    name: ' '
    view: no
    entities:
     - sensor.stats_downstairs_air
     - sensor.stats_upstairs_air
     - sensor.stats_downstairs_air_week
     - sensor.stats_upstairs_air_week
     - sensor.stats_downstairs_air_30
     - sensor.stats_upstairs_air_30
  hvac_stats_heat:
    name: ' '
    view: no
    entities:
     - sensor.stats_downstairs_heat
     - sensor.stats_upstairs_heat
     - sensor.stats_downstairs_heat_week
     - sensor.stats_upstairs_heat_week
     - sensor.stats_downstairs_heat_30
     - sensor.stats_upstairs_heat_30     
## Switches for Node Red Alexa Temperature Announcements     
input_boolean:
  downstairs_temp:
    name: Downstairs Temperature
    initial: off
  downstairs_humidity:
    name: Downstairs Humidity
    initial: off    
  garage_temp:
    name: Garage Temperature
    initial: off
  garage_humidity:
    name: Garage Humidity
    initial: off
  upstairs_temp:
    name: Upstairs Temperature
    initial: off
  upstairs_humidity:
    name: Upstairs Humidity
    initial: off
  downstairs_hotter:
    name: Downstairs Hotter
    initial: off
  downstairs_cooler:
    name: Downstairs Cooler
    initial: off
  upstairs_hotter:
    name: Upstairs Hotter
    initial: off
  upstairs_cooler:
    name: Upstairs Cooler
    initial: off
    
 
sensor:

## http://192.168.1.226        
## Garage Climate Sensors Minus 1 Degree Adjustment        
  - platform: mqtt
    state_topic: 'tele/garage_light2/SENSOR'
    name: 'Garage Temp' #AM2302
    icon: mdi:thermometer
    unit_of_measurement: '°F'
    value_template: '{{ value_json.AM2301.Temperature | float - 1 }}'
    expire_after: 300
  - platform: mqtt
    state_topic: 'tele/garage_light2/SENSOR'
    name: 'Garage Humidity'
    icon: mdi:water-percent
    unit_of_measurement: '%'
    value_template: '{{ value_json.AM2301.Humidity }}'
    expire_after: 300
    
    
    
  - platform: template
    sensors:
       
       
      downstairs_1:
        value_template: "{{ states('sensor.temperature_158d0002d479bb') | round(1) }}"
        unit_of_measurement: °F
      downstairs_2:
        value_template: "{{ states('sensor.temperature_158d0002e22c86') | round(1) }}"    
        unit_of_measurement: °F        
      downstairs_3:
        value_template: "{{ states('sensor.temperature_158d0002d45555') | round(1) }}"
        unit_of_measurement: °F
      upstairs_1:
        value_template: "{{ states('sensor.temperature_158d0002c8bf77') | round(1) }}"
        unit_of_measurement: °F
      upstairs_2:
        value_template: "{{ states('sensor.temperature_158d0002d47aa1') | round(1) }}"
        unit_of_measurement: °F
      upstairs_3:
        value_template: "{{ states('sensor.temperature_158d0002d478d3') | round(1) }}"
        unit_of_measurement: °F
        
## Climate Sensors Templated On One Line For Display Purposes    
      
      sensor1_oneline:
        friendly_name: "Office"
        value_template: >
          {{states.sensor.downstairs_1.state}}° - {{states.sensor.humidity_158d0002d479bb.state}}% - {{states.sensor.humidity_158d0002d479bb.attributes.battery_level}}%  
      sensor2_oneline:
        friendly_name: "Kitchen"
        value_template: > 
          {{states.sensor.downstairs_2.state}}° - {{states.sensor.humidity_158d0002e22c86.state}}% - {{states.sensor.humidity_158d0002e22c86.attributes.battery_level}}%
      sensor3_oneline:
        friendly_name: "Bedroom"
        value_template: >
          {{states.sensor.downstairs_3.state}}° - {{states.sensor.humidity_158d0002d45555.state}}% - {{states.sensor.humidity_158d0002d45555.attributes.battery_level}}%       
      sensor4_oneline:
        friendly_name: "Abigail"
        value_template: >
          {{states.sensor.upstairs_1.state}}° - {{states.sensor.humidity_158d0002c8bf77.state}}% - {{states.sensor.humidity_158d0002c8bf77.attributes.battery_level}}%  
      sensor5_oneline:
        friendly_name: "Deuce"
        value_template: >
          {{states.sensor.upstairs_2.state}}° - {{states.sensor.humidity_158d0002d47aa1.state}}% - {{states.sensor.humidity_158d0002d47aa1.attributes.battery_level}}%        
      sensor6_oneline:
        friendly_name: "Benjamin"
        value_template: >
          {{states.sensor.upstairs_3.state}}° - {{states.sensor.humidity_158d0002d478d3.state}}% - {{states.sensor.humidity_158d0002d478d3.attributes.battery_level}}%       
        
      garage_climate_oneline:
        friendly_name: "Garage"
        value_template: >
          {{states.sensor.garage_temp.state}}°   {{states.sensor.garage_humidity.state}}%   
          
  - platform: min_max
    name: "Average Downstairs Temp"
    type: "mean"
    round_digits: 1
    entity_ids:
      - sensor.downstairs_1
      - sensor.downstairs_2
      - sensor.downstairs_3
  - platform: min_max
    name: "Average Downstairs Humidity"
    type: "mean"
    round_digits: 1
    entity_ids:
      - sensor.humidity_158d0002d479bb
      - sensor.humidity_158d0002e22c86
      - sensor.humidity_158d0002d45555

  - platform: min_max
    name: "Average Upstairs Temp"
    type: "mean"
    round_digits: 1
    entity_ids:
      - sensor.upstairs_1
      - sensor.upstairs_2
      - sensor.upstairs_3
  - platform: min_max
    name: "Average Upstairs Humidity"
    type: "mean"
    round_digits: 1
    entity_ids:      
      - sensor.humidity_158d0002c8bf77
      - sensor.humidity_158d0002d47aa1
      - sensor.humidity_158d0002d478d3        
