homeassistant:
  customize:
    switch.downstairs_fan:
      icon: mdi:fan
    switch.upstairs_fan:
      icon: mdi:fan
    climate.upstairs_ac:
      icon: mdi:air-conditioner
    climate.upstairs_furnace:
      icon: mdi:radiator
    climate.downstairs_ac:
      icon: mdi:air-conditioner
    climate.downstairs_furnace:
      icon: mdi:radiator
    input_boolean.climate_disable_systems:
      icon: mdi:toggle-switch-off-outline
    input_boolean.climate_select_mode:
      icon: mdi:toggle-switch-off-outline

automation:

##########################################################
##                                                      ##
##             FAN CONTROLS - CALL WITH AC              ##
##                                                      ##
##########################################################
           
## Downstairs AC Call On/Off Controls Fan Switch
  - id: Downstairs_AC_On
    alias: Downstairs AC On Turn Downstairs Fan On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.downstairs_ac
        to: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.downstairs_fan
  - id: Downstairs_AC_Off
    alias: Downstairs AC Off Turn Downstairs Fan Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.downstairs_ac
        to: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.downstairs_fan
        
## Upstairs AC Call On/Off Controls Fan Switch
  - id: Upstairs_AC_On
    alias: Upstairs AC On Turn Upstairs Fan On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.upstairs_ac
        to: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.upstairs_fan
  - id: Upstairs_AC_Off
    alias: Upstairs AC Off Turn Upstairs Fan Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.upstairs_ac
        to: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.downstairs_fan 
        
## Note: You Do Not Control the Fan When Calling for Heat, The Unit Does That According To It's Safety Measures
##########################################################
##                                                      ##
##         OPERATION MODES - HA START, RESTART          ##
##                                                      ##
##########################################################

## Set Both Systems To AC On Start If Set To AC Mode

  - id: ac_mode_restart
    alias: climate ac mode restart
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.climate_disable_systems
          state: 'off'
        - condition: state
          entity_id: input_boolean.climate_select_mode
          state: 'off'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'off' 

## Set Both Systems To Heat On Start If Set To Heat Mode          
          
  - id: heat_mode_restart
    alias: climate heat mode restart
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.climate_disable_systems
          state: 'off'
        - condition: state
          entity_id: input_boolean.climate_select_mode
          state: 'on'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'heat'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'heat'          

##########################################################
##                                                      ##
##           OPERATION MODES - MANUAL SWITCHES          ##
##                                                      ##
##########################################################          

## Set Both Systems to AC On Mode Change
             
  - id: ac_mode_switch
    alias: climate ac mode switch
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.climate_select_mode
        from: 'on'
        to: 'off'
    condition:
      condition: state
      entity_id: input_boolean.climate_disable_systems
      state: 'off'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'off'

## Set Both Systems to Heat On Mode Change                  
          
  - id: heat_mode_switch
    alias: climate heat mode switch
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.climate_select_mode
        from: 'off'
        to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.climate_disable_systems
      state: 'off'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'heat'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'heat'

## Disable All Systems - Windows Open, Service Etc.          
          
  - id: disable_climate_systems
    alias: climate disable systems
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.climate_disable_systems
        from: 'off'
        to: 'on'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'off'

## Restore Both Systems When Renabled According To Your Mode Selection          

  - id: restore_climate_systems_ac
    alias: climate restore systems ac
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.climate_disable_systems
        from: 'on'
        to: 'off'
    condition:
      condition: state
      entity_id: input_boolean.climate_select_mode
      state: 'off'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'off'   

  - id: restore_climate_systems_heat
    alias: climate restore systems heat
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.climate_disable_systems
        from: 'on'
        to: 'off'
    condition:
      condition: state
      entity_id: input_boolean.climate_select_mode
      state: 'on'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'heat'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'heat'
          
##########################################################
##                                                      ##
##       ONLY ONE SYSTEM AT A TIME, AC OR HEAT          ##
##                This Is Important!!!                  ##
##                                                      ##
##########################################################

## Turning Heat Thermostat On Turns Off AC Thermostat - Downstairs
  - id: Downstairs_Heat_Mode
    alias: Downstairs Heat Disables AC
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: "{{ (states.climate.downstairs_furnace.attributes.operation_mode) == 'heat' }}"
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'off'
## Turning AC Thermostat On Turns Off Heat Thermostat - Downstairs
  - id: Downstairs_AC_Mode
    alias: Downstairs AC Disables Heat
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: "{{ (states.climate.downstairs_ac.attributes.operation_mode) == 'cool' }}"
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'off'
                
## Turning Heat Thermostat On Turns Off AC Thermostat - Upstairs
  - id: Upstairs_Heat_Mode
    alias: Upstairs Heat Disables AC
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: "{{ (states.climate.upstairs_furnace.attributes.operation_mode) == 'heat' }}"
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'off'
## Turning AC Thermostat On Turns Off Heat Thermostat - Upstairs
  - id: Upstairs_AC_Mode
    alias: Upstairs AC Disables Heat
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: "{{ (states.climate.upstairs_ac.attributes.operation_mode) == 'cool' }}"
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'off'


          
## THERMOSTATS CONFIGURATION          
climate:
## Downstairs Heat Thermostat
  - platform: generic_thermostat
    name: Downstairs Heat
    heater: switch.downstairs_furnace
    target_sensor: sensor.downstairs_temp
    min_temp: 65
    max_temp: 75
    min_cycle_duration:
      minutes: 15
    initial_operation_mode: "off"
    target_temp: 70
    away_temp: 67
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    
## Downstairs AC Thermostat
  - platform: generic_thermostat
    name: Downstairs AC
    heater: switch.downstairs_ac
    target_sensor: sensor.downstairs_temp
    min_temp: 65
    max_temp: 75
    initial_operation_mode: "off"    
    min_cycle_duration:
      minutes: 10
    target_temp: 73
    away_temp: 75
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    ac_mode: true
    
## Upstairs Heat Thermostat
  - platform: generic_thermostat
    name: Upstairs Furnace
    heater: switch.upstairs_furnace
    target_sensor: sensor.upstairs_temp
    min_temp: 65
    max_temp: 75
    min_cycle_duration:
      minutes: 15
    initial_operation_mode: "off"
    target_temp: 70
    away_temp: 67
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    
## Upstairs AC Thermostat
  - platform: generic_thermostat
    name: Upstairs AC
    heater: switch.upstairs_ac
    target_sensor: sensor.upstairs_temp
    min_temp: 65
    max_temp: 75
    initial_operation_mode: "off"    
    min_cycle_duration:
      minutes: 10
    target_temp: 73
    away_temp: 75
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    ac_mode: true  

## Boolean for Alexa/User to Control Both Systems
input_boolean:
  climate_select_mode:
    name: Climate Mode - Off=AC   On=Heat    
  climate_disable_systems:
    name: Disable HVAC Systems
    
## Groups For Entities In This Package 
group:
  down_thermostat:
    name: Downstairs AC/Heat
    view: no
    entities:
     - climate.downstairs_ac
     - climate.downstairs_heat
     - switch.downstairs_fan
  up_thermostat:
    name: Upstairs AC/Heat
    view: no
    entities:        
     - climate.upstairs_ac
     - climate.upstairs_furnace
     - switch.upstairs_fan
  thermostat_control:
    name: Thermostats Control
    view: no
    entities:
     - input_boolean.climate_select_mode
     - input_boolean.climate_disable_systems
     

        
## Thermostat Switches For Climate Control          
switch:
  - platform: mqtt
    name: "Downstairs Fan"
    command_topic: "cmnd/downstairs_thermostat/POWER1"
    state_topic: "stat/downstairs_thermostat/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Downstairs AC"
    command_topic: "cmnd/downstairs_thermostat/POWER2"
    state_topic: "stat/downstairs_thermostat/POWER2"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Downstairs Furnace"
    command_topic: "cmnd/downstairs_thermostat/POWER3"
    state_topic: "stat/downstairs_thermostat/POWER3"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Upstairs Fan"
    command_topic: "cmnd/upstairs_thermostat/POWER1"
    state_topic: "stat/upstairs_thermostat/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Upstairs AC"
    command_topic: "cmnd/upstairs_thermostat/POWER2"
    state_topic: "stat/upstairs_thermostat/POWER2"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Upstairs Furnace"
    command_topic: "cmnd/upstairs_thermostat/POWER3"
    state_topic: "stat/upstairs_thermostat/POWER3"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false       
    
    