## This Variation is Solely For using a Sonoff 4ch/Pro to Control 2 Units with No Manual Fan

## 4Ch Sonoff Wiring
## 1 - (N.C. - empty) (COM - 24v Red Wire from Downstairs Unit) (N.O. - AC/Fan Call yellow & green wires together)
## 2 - (N.C. - empty) (COM - 24v Red Wire from Downstairs Unit) (N.O. - Furance Call white wire)
## 3 - (N.C. - empty) (COM - 24v Red Wire from Upstairs Unit) (N.O. - AC/Fan Call yellow & green wires together)
## 4 - (N.C. - empty) (COM - 24v Red Wire from Upstairs Unit) (N.O. - Furnace Call white wire)

homeassistant:
  customize:
    climate.upstairs_ac:
      icon: mdi:air-conditioner
    climate.upstairs_furnace:
      icon: mdi:radiator
    climate.downstairs_ac:
      icon: mdi:air-conditioner
    climate.downstairs_furnace:
      icon: mdi:radiator
    input_boolean.climate_disable_systems:
      icon: mdi:toggle-switch-off-outline
    input_boolean.climate_select_mode:
      icon: mdi:toggle-switch-off-outline    
    
automation:   

## Note: No Automations for Fan Switches Required In This Configuration!!

## For Alexa make 4 routines - 
## Alexa, turn on the air - input_boolean.climate_select_mode - off
## Alexa, turn on the heat - input_boolean.climate_select_mode - on
## Alexa, turn off thermostats - input_boolean.climate_disable_systems - on
## Alexa, turn on thermostats - input_boolean.climate_disable_systems - off
        
##########################################################
##                                                      ##
##         OPERATION MODES - HA START, RESTART          ##
##                                                      ##
##########################################################

## Set Both Systems To AC On Start If Set To AC Mode

  - id: ac_mode_restart
    alias: climate ac mode restart
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.climate_disable_systems
          state: 'off'
        - condition: state
          entity_id: input_boolean.climate_select_mode
          state: 'off'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'off' 

## Set Both Systems To Heat On Start If Set To Heat Mode          
          
  - id: heat_mode_restart
    alias: climate heat mode restart
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.climate_disable_systems
          state: 'off'
        - condition: state
          entity_id: input_boolean.climate_select_mode
          state: 'on'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'heat'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'heat'          

##########################################################
##                                                      ##
##           OPERATION MODES - MANUAL SWITCHES          ##
##                                                      ##
##########################################################          

## Set Both Systems to AC On Mode Change
             
  - id: ac_mode_switch
    alias: climate ac mode switch
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.climate_select_mode
        from: 'on'
        to: 'off'
    condition:
      condition: state
      entity_id: input_boolean.climate_disable_systems
      state: 'off'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'off'

## Set Both Systems to Heat On Mode Change                  
          
  - id: heat_mode_switch
    alias: climate heat mode switch
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.climate_select_mode
        from: 'off'
        to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.climate_disable_systems
      state: 'off'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'heat'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'heat'

## Disable All Systems - Windows Open, Service Etc.          
          
  - id: disable_climate_systems
    alias: climate disable systems
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.climate_disable_systems
        from: 'off'
        to: 'on'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'off'

## Restore Both Systems When Renabled According To Your Mode Selection          

  - id: restore_climate_systems_ac
    alias: climate restore systems ac
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.climate_disable_systems
        from: 'on'
        to: 'off'
    condition:
      condition: state
      entity_id: input_boolean.climate_select_mode
      state: 'off'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'cool'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'off'   

  - id: restore_climate_systems_heat
    alias: climate restore systems heat
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.climate_disable_systems
        from: 'on'
        to: 'off'
    condition:
      condition: state
      entity_id: input_boolean.climate_select_mode
      state: 'on'
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'heat'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'off'
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'heat'

                    
##########################################################
##                                                      ##
##       ONLY ONE SYSTEM AT A TIME, AC OR FURNACE       ##
##                This Is Important!!!                  ##
##                                                      ##
##########################################################

## Turning Furnace Thermostat On Turns Off AC Thermostat - Downstairs
  - id: Climate Downstairs_Furnace_Mode
    alias: Climate Downstairs Furnace Disables AC
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ (states.climate.downstairs_furnace.attributes.operation_mode) == 'heat' }}"
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_ac
          operation_mode: 'off'
          
## Turning AC Thermostat On Turns Off Furnace Thermostat - Downstairs
  - id: Climate Downstairs_AC_Mode
    alias: Climate Downstairs AC Disables Furnace
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ (states.climate.downstairs_ac.attributes.operation_mode) == 'cool' }}"
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.downstairs_furnace
          operation_mode: 'off'
                
## Turning Furnace Thermostat On Turns Off AC Thermostat - Upstairs
  - id: Climate Upstairs_Furnace_Mode
    alias: Upstairs Furnace Disables AC
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ (states.climate.upstairs_furnace.attributes.operation_mode) == 'heat' }}"
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_ac
          operation_mode: 'off'
          
## Turning AC Thermostat On Turns Off Furnace Thermostat - Upstairs
  - id: Climate Upstairs_AC_Mode
    alias: Climate Upstairs AC Disables Furnace
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ (states.climate.upstairs_ac.attributes.operation_mode) == 'cool' }}"
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs_furnace
          operation_mode: 'off'
          

           
## THERMOSTATS & CONFIGURATION          
climate:

## Downstairs AC Thermostat
  - platform: generic_thermostat
    name: Downstairs AC
    heater: switch.downstairs_air_call
    target_sensor: sensor.downstairs_temp
    min_temp: 65
    max_temp: 75
    initial_operation_mode: "off"    
    min_cycle_duration:
      minutes: 10
    target_temp: 73
    away_temp: 75
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    ac_mode: true
    
## Downstairs Furnace Thermostat
  - platform: generic_thermostat
    name: Downstairs Furnace
    heater: switch.downstairs_furnace_call
    target_sensor: sensor.downstairs_temp
    min_temp: 65
    max_temp: 75
    min_cycle_duration:
      minutes: 15
    initial_operation_mode: "auto"
    target_temp: 70
    away_temp: 67
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    
## Upstairs AC Thermostat
  - platform: generic_thermostat
    name: Upstairs AC
    heater: switch.upstairs_air_call
    target_sensor: sensor.upstairs_temp
    min_temp: 65
    max_temp: 75
    initial_operation_mode: "off"    
    min_cycle_duration:
      minutes: 10
    target_temp: 73
    away_temp: 75
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    ac_mode: true  
    
## Upstairs Furnace Thermostat
  - platform: generic_thermostat
    name: Upstairs Furnace
    heater: switch.upstairs_furnace_call
    target_sensor: sensor.upstairs_temp
    min_temp: 65
    max_temp: 75
    min_cycle_duration:
      minutes: 15
    initial_operation_mode: "auto"
    target_temp: 70
    away_temp: 67
    cold_tolerance: 0.5
    hot_tolerance: 0.5


## Groups For Entities In This Package 
group:
  thermostats:
    name: Thermostat Control
    control: hidden
    view: no
    entities:
     - climate.downstairs_ac
     - climate.downstairs_furnace
     - climate.upstairs_ac
     - climate.upstairs_furnace
     - input_boolean.climate_select_mode
     - input_boolean.climate_disable_systems

## Boolean for Alexa/User to Control Both Systems
input_boolean:
  climate_select_mode:
    name: Climate Mode - Off=AC   On=Heat    
  climate_disable_systems:
    name: Disable HVAC Systems

    
## Thermostat Switches For Climate Control          
switch:
  - platform: mqtt
    name: "Downstairs Air Call"
    command_topic: "cmnd/thermostat/POWER1"
    state_topic: "stat/thermostat/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Downstairs Furnace Call"
    command_topic: "cmnd/thermostat/POWER2"
    state_topic: "stat/thermostat/POWER2"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Upstairs Air Call"
    command_topic: "cmnd/thermostat/POWER3"
    state_topic: "stat/thermostat/POWER3"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Upstairs Furnace Call"
    command_topic: "cmnd/thermostat/POWER4"
    state_topic: "stat/thermostat/POWER4"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: false       
    

    